import type { Metadata } from "next";

import { Poppins } from "next/font/google";

import "./globals.css";

import Provider from "@/providers";

const FontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "EduNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${FontPoppins.className} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
